### ISSUE TITLE
📚 [Documentation / WorkFlow] - Title

### ISSUE THREAD

**Issue by Soumyajit2825** [anmode/Move-to-nextJS#336]
### Description ✍️

![Screenshot 2023-05-20 220647](https://github.com/anmode/grabtern-frontend/assets/100519291/b57b31fa-c462-4c6c-847d-cffcad8ed174)
<br>
I want to add a folding switch in the table of contents menu like this in this readme file
<br>
![Screenshot 2023-06-15 234255](https://github.com/anmode/grabtern-frontend/assets/100519291/d72cc187-8b8b-4ce5-90f8-5661aa0712bd)
<br>
Here in the 4th point there will be push in place of "pull" which is a typo.
I want to fix these simple and minor documentation issues

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
It would be great.. if you can documentation of project with the folder structure... May it help other contributors

**Comment by Soumyajit2825** [comment]
@anmode PR created please check
#339
