### ISSUE TITLE
🐞 [BUG] - Validation issue in contact page fields

### ISSUE THREAD

**Issue by 777Prabhjot** [anmode/Move-to-nextJS#538]
### Description

In the contact page there is no front-end validation present. there should be an validation for each field so that an empty data request not get submitted to the backend.

### Current behaviour

Empty values are getting submitted to the backend because there is no fields validation for contact page right now

### Expected behaviour

Validations should be implemented for the contact page fields. so that empty data request not got submit to the backend.

### Reproduction steps

```bash
1. Go to 'Contact page'
2. Click on 'Send button'
3. Empty data request is getting submitted to the backend
```

### Screenshots

https://github.com/anmode/grabtern-frontend/assets/68184118/7bd96df4-9e87-44c5-883b-3f8dbd21865b

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
it has been fixed.. see the development version!
