### ISSUE TITLE
🚀 [Feature Request] - User Dashboard Improvement

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#768]
### Is your feature request related to a problem ? Please describe. ✍️

Improve the UI of user dashboard

### Describe briefly how you would implement this enhancement.

```bash
Null
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by rishuraj1** [comment]
Hey @anmode , I would really like to work on this, can you give me a heads up. thanks.

**Comment by anmode** [comment]
sure!

**Comment by Luckydhingra** [comment]
Hi ! @anmode I am also like to work on this issue , could u assign me this one :D

**Comment by anmode** [comment]
@rishuraj1 are you working on this issue??

**Comment by anmode** [comment]
> Hi ! @anmode I am also like to work on this issue , could u assign me this one :D

it is now assigned to Rishu.. if he agrees you can takeover

**Comment by Luckydhingra** [comment]
> > Hi ! @anmode I am also like to work on this issue , could u assign me this one :D
> 
> it is now assigned to Rishu.. if he agrees you can takeover

@rishuraj1 are u working on it?

**Comment by rishuraj1** [comment]
@Luckydhingra , @anmode   hi, yes I am working on it now, I was a bit occupied with exams..its over now

**Comment by rishuraj1** [comment]
@anmode  apologies for the delay..... just a quick update:
I have added a usericon instead of a pfp in case of a new user 
<img width="960" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/d655c8af-87f1-43c3-9d11-6af8a0a38620">

also when a user uploads the pfp, ofcourse it shows the pfp
![image](https://github.com/anmode/grabtern-frontend/assets/47839626/e346f5f5-20b0-4dd5-9521-cc025dc74c32)

also added a bookings card.
Tell me if any modifications required,

will be working on bookings card

**Comment by anmode** [comment]
All look good rishu!

**Comment by anmode** [comment]
Booking will not be card see the section of mentor with slitght change in UX like in place mentee will be there mentor name.: you can use that code
<img width="694" alt="Screenshot 2023-10-14 at 11 13 13 AM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/a251b44b-2878-46a3-b065-353f50b4fc40">

**Comment by anmode** [comment]
> > > Hi ! @anmode I am also like to work on this issue , could u assign me this one :D
> > 
> > 
> > it is now assigned to Rishu.. if he agrees you can takeover
> 
> @rishuraj1 are u working on it?

@Luckydhingra there more issues or you may create any issue or work on that like dark mode feature.. if you can do it!
