### ISSUE TITLE
🚀 [Feature Request] - Improve the Session booking

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#770]
### Is your feature request related to a problem ? Please describe. ✍️

Book session path needs to improved and UI needs to updated.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Just see the book session route and update the UI accordingly
2. Date to calculated by day
```

### Additional context or screenshots

currently: <img width="245" alt="Screenshot 2023-10-06 at 5 00 03 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/de2fdd2d-e766-4aaa-b93f-5211e64539f5">

we want: 
![WhatsApp Image 2023-09-19 at 6 59 49 AM (1)](https://github.com/anmode/grabtern-frontend/assets/88332977/28484817-3b2b-4196-8e9a-e6aacdcc71b3)

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by sudarshanmg** [comment]
Hi @anmode. I would be glad to work on this issue.

**Comment by anmode** [comment]
cool!

**Comment by sudarshanmg** [comment]
Okay :sweat: . I need some pointers here, apparently  I am not able to access the page in my local machine.
I guess because I am not able access the database through localhost. Is there any other way to access the bookSession page? Also, I think there's a typo in Book "dession" type

**Comment by anmode** [comment]
please in that case , can you use our production server?
https://api.grabtern.com

**Comment by anmode** [comment]
yeah you can correct that typo too

**Comment by anmode** [comment]
@sudarshanmg are you there?

**Comment by tech-bash** [comment]
Kindly assign it to me!

**Comment by rishuraj1** [comment]
Hello @anmode , I would like to try this, if anyone is not contributing to this.

**Comment by anmode** [comment]
okkk
