### ISSUE TITLE
🐞 [BUG] - Sign in page not working

### ISSUE THREAD

**Issue by tech-bash** [anmode/Move-to-nextJS#777]
### Description

On running the application locally when I'm trying to sign in, the app is throwing the following error 

``Application error: a client-side exception has occurred (see the browser console for more information).``
This might be a problem that has occurred after the latest production..

### Current behaviour

Cannot reach to the `sign in` page

### Expected behaviour

Sign in should be accessible locally too ...

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/76992919/32be17a0-a7c1-4b70-ab07-e2a9e3eafe57)

### Browsers

Firefox, Chrome

### OS

Linux

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by inbuilt-aura** [comment]
@tech-bash, assign me and label this as hacktoberfest, will fix this

**Comment by tech-bash** [comment]
Thanks @anmode for doing the work!

**Comment by inbuilt-aura** [comment]
@anmode, can you tell which branch has this issue?

**Comment by anmode** [comment]
@tech-bash ? i think @inbuilt-aura you can take over that dark mode issue.. I'll look at this issue thanks! Actually it need some prod variables values which are kept private for some reason

**Comment by inbuilt-aura** [comment]
@anmode need to talk seriously.

**Comment by inbuilt-aura** [comment]
@anmode there are tons of bugs in the site, let me give you an example.
![Screenshot (83)](https://github.com/anmode/grabtern-frontend/assets/74290697/9b7609c0-7712-4862-979c-2429e9f95447)
This is not a bug, how it will work when there is no backend.We need to check everything from start and fix all the bug first

**Comment by inbuilt-aura** [comment]
@anmode, close this issue as this is not valid.I have created new issue for same.Label it as hacktoberfest and accept pr.

**Comment by tech-bash** [comment]
> @anmode there are tons of bugs in the site, let me give you an example. ![Screenshot (83)](https://user-images.githubusercontent.com/74290697/276571765-9b7609c0-7712-4862-979c-2429e9f95447.png) This is not a bug, how it will work when there is no backend.We need to check everything from start and fix all the bug first

Ig the backend was deployed already, so we don't need to setup the backend in every local machine!

**Comment by anmode** [comment]
yes backend is https://demoapi.grabtern.com

**Comment by tech-bash** [comment]
@anmode the issue is still on right?

**Comment by anmode** [comment]
No no, actually this issue need google sign in variable value and it can't be public due to security issue so it would be good to close it!

**Comment by tech-bash** [comment]
Ahh, so you will solve it in your own private repo, right?
