### ISSUE TITLE
🚀 [Feature Request] - A support chat section

### ISSUE THREAD

**Issue by rishuraj1** [anmode/Move-to-nextJS#779]
### Is your feature request related to a problem ? Please describe. ✍️

We might want to build a support chat section to answer the queries.
eg:
<img width="222" alt="image" src="https://github.com/anmode/grabtern-frontend/assets/47839626/2aed2837-d9ce-4137-8e14-56da2c869c7d">

I want to work on this, please assign me this under hacktoberfest. Thank You !

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
it would be cool!
