### ISSUE TITLE
🐞 [BUG] - Folder structure needs to be fixed.

### ISSUE THREAD

**Issue by inbuilt-aura** [anmode/Move-to-nextJS#780]
### Description

A lot of bugs are there while we are starting our npm run dev server and some of the files and issues are repeated causing repeating issues even after installing again.
![Screenshot (84)](https://github.com/anmode/grabtern-frontend/assets/74290697/9330a94b-4ced-4805-a9cd-402376bca780)

Needs to check from scratch.
![Screenshot (85)](https://github.com/anmode/grabtern-frontend/assets/74290697/aa09069f-19a7-4b3b-990c-f8e5c0ca00d0)

### Current behaviour

Its running but with a lot of error as its nextjs and only frontend is loading..

### Expected behaviour

Should have run without any other issue but got this.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

GSSoC2023, Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
1. Those terminal message or console message are due to PWA ( see if you can work on PWA , I can create multiple issue based on PWA
2.  Please pull the latest changes in `develop` branch, apidata issue is fixed and please use this as backend url and make sure node_env is on test mode.
backend url: https://demoapi.grabtern.com

**Comment by inbuilt-aura** [comment]
@anmode, I will look into it and revert back to you.

**Comment by inbuilt-aura** [comment]
@anmode assign me and will raise current pr as per folder stracture

**Comment by anmode** [comment]
hey @inbuilt-aura ? so sorry! I missed this last message... you can create PR.

**Comment by inbuilt-aura** [comment]
@anmode sure!

**Comment by inbuilt-aura** [comment]
@anmode, sorry for not being active. Can i ask that the folder structure will be same or you need some changes. If yes, do let me know so that i can raise a PR.

**Comment by anmode** [comment]
i think folder structure is ok and it could be bigger change.. may lead to many issues!
