### ISSUE TITLE
🚀 [Feature Request] - Fix loader and design accross the grabtern

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#782]
### Is your feature request related to a problem ? Please describe. ✍️

There are loader on api fetch or any button click , you just need to use nice loader and responsive.
As some places there is small loader ( as compared to surrounding text/UX)
So this all needs to fixed.

As mentor list page has this logo ( not looking good should be matching by grabtern)
<img width="392" alt="Screenshot 2023-10-19 at 10 20 37 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/64f2de9e-96fd-4124-a808-6df45db390c8">

Same as other places.

### Describe briefly how you would implement this enhancement.

```bash
Easy, just use loader and provide is properites and make it responsive.
Make sure that api response can be successful and it case of error loader should be revert back to button ( if button replaces by loader on api fetch)
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
If need more clarity regarding this issue let me know! Thanks

**Comment by ShagunDubey1** [comment]
Can you please specify where this loader is located in the mentor list? I have gone through the site, but the design of the loader is different.

**Comment by anmode** [comment]
yeah you can use your own loader, just create a folder with custom loader and apply loader at all possible places the main things is loader should be responsive and should look good!

See loader comes when there is processing so when on running on localhost  ( mentor list) 
you will see the loader but it does not look good!

**Comment by ShagunDubey1** [comment]
Okay, could you assign this to me?

**Comment by anmode** [comment]
yeah sure!

**Comment by anmode** [comment]
@shagundubey29 are you working on it? if any issue let me know

**Comment by ShagunDubey1** [comment]
Okay
