### ISSUE TITLE
🚀 [Feature Request] - Improve error handling ( UX work)

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#783]
### Is your feature request related to a problem ? Please describe. ✍️

We had not consider all case and error response...  
we have Taostify to display error/success.
you just have to work on all cases frontend can display error which can be shown by frontend.. 

### Describe briefly how you would implement this enhancement.

```bash
for eg:
If any field is blank , it should be show error.
The thing is to consider all possible case of error so user can get what causing error. 
Major area: form filling
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by rishuraj1** [comment]
@anmode  please assign me to this as well, should be an easy fix as I am already working on frontend. Thanks

**Comment by anmode** [comment]
Cool, Btw Rishu let me know if any meet require.. because for this issue you have to think of all cases which type of error may arise and user should be acknowled for that and if there is any priority error we should get email ( this we will apply or you can use contact us api for that)

**Comment by rishuraj1** [comment]
@anmode  alright will take care.

**Comment by inbuilt-aura** [comment]
@anmode is this repo open?

**Comment by rishuraj1** [comment]
@inbuilt-aura  yes i am working on it.

**Comment by inbuilt-aura** [comment]
@rishuraj1 ok let me know if you need help
