### ISSUE TITLE
📚 [Documentation / WorkFlow] - Add social links in readme ( with nice icons)

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#784]
### Description ✍️

Here is discord: https://discord.gg/9zRCUmUtA2
linkedin: https://www.linkedin.com/company/grabtern/
website: www.grabtern.com

and backend url: api.grabtern.com

add insta icon too.. I'll provide link soon!

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by ghoshvidip26** [comment]
Please assign this issue to me.
