### ISSUE TITLE
🚀 [Feature Request] - add log out button in the sidebar

### ISSUE THREAD

**Issue by sayyedarib** [anmode/Move-to-nextJS#789]
### Is your feature request related to a problem ? Please describe. ✍️

![Screenshot from 2023-10-22 11-13-54](https://github.com/anmode/grabtern-frontend/assets/90370535/1e3d24f8-a7ed-4428-8392-4485a9650480)
add logout button in sidebar

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 signup/login 
2. Step 2 go to dashboard
```

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by ArslanYM** [comment]
> ### Is your feature request related to a problem ? Please describe. ✍️
> ![Screenshot from 2023-10-22 11-13-54](https://user-images.githubusercontent.com/90370535/277147672-1e3d24f8-a7ed-4428-8392-4485a9650480.png) add logout button in sidebar
> 
> ### Describe briefly how you would implement this enhancement.
> ```shell
> Some steps to implement this enhancement-
> 1. Step 1 signup/login 
> 2. Step 2 go to dashboard
> ```
> 
> ### Additional context or screenshots
> _No response_
> 
> ### Are you contributing for a program?
> Other
> 
> ### Code of Conduct
> * [x]  I have read and agree to the Contributing Guidelines of this project.

Can I work on this?

**Comment by sayyedarib** [comment]
@ArslanYM you can start working.
There's already a logout button inside Home tab component, but we need to place it in sidebar so that user need not to navigate back to home tab whenever he/she wants to logout.

**Comment by ArslanYM** [comment]
> @ArslanYM you can start working. There's already a logout button inside Home tab component, but we need to place it in sidebar so that user need not to navigate back to home tab whenever he/she wants to logout.

Tried to setup the project locally, throws a bunch of errors. Heres one :

![1](https://github.com/anmode/grabtern-frontend/assets/104521101/00ac7753-6d12-4779-95c0-47e10269b5cc)

**Comment by sayyedarib** [comment]
@ArslanYM please update your develop branch and let me know if the issue is fixed.

**Comment by anmode** [comment]
> > @ArslanYM you can start working. There's already a logout button inside Home tab component, but we need to place it in sidebar so that user need not to navigate back to home tab whenever he/she wants to logout.
> 
> Tried to setup the project locally, throws a bunch of errors. Heres one :
> 
> ![1](https://user-images.githubusercontent.com/104521101/277351460-00ac7753-6d12-4779-95c0-47e10269b5cc.png)

hi @ArslanYM .... Did you run this command `npm run dev` if this problem arise. hope it would be solved by @sayyedarib patch update.. or you can comment out  google code for developement for sometime

**Comment by ArslanYM** [comment]
> @ArslanYM please update your develop branch and let me know if the issue is fixed.

I have updated my fork to the latest changes. Still shows a few errors. Can you tell me what version of npm is the project running on ?

**Comment by anmode** [comment]
it is 16 version!

**Comment by Afterdie** [comment]
I'd like to work on this issue

**Comment by anmode** [comment]
cool @Afterdie

**Comment by Albert-2** [comment]
hey @anmode....
I would really like to contribute to this feature can you please assign me the same under codepeak'23; if no one is still working on it 
THANK YOU FOR CONSIDERING....... :)

**Comment by anmode** [comment]
@Afterdie are you working? if not then I'll assign @Albert-2

**Comment by Albert-2** [comment]
hey @anmode
Assign me the issue please....!
Thank you for considering

**Comment by ShivamAgarwal-code** [comment]
@anmode kindly assign me this issue if no one is working on it..
