### ISSUE TITLE
🚀 [Feature Request] - No scroll  bar in home page

### ISSUE THREAD

**Issue by Developer-Swati** [anmode/Move-to-nextJS#793]
### Is your feature request related to a problem ? Please describe. ✍️

I came across that there is no scrollbar on home page 

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Developer-Swati** [comment]
Please assign this issue to me under Hacktober  fest2023

**Comment by anmode** [comment]
We follow scrollbar less methodology! sorry we do not need this feat.. you can create issue to create a blog page or you can pick more issues, thanks!

**Comment by Developer-Swati** [comment]
Ok then I can work on blog page
