### ISSUE TITLE
🚀 [Feature Request] - Make blog feat to work

### ISSUE THREAD

**Issue by Developer-Swati** [anmode/Move-to-nextJS#795]
### Is your feature request related to a problem ? Please describe. ✍️

I want to add a blog that will be related to the open source contribution that will cover the following points:-

1. Intro to open source 
2. Prerequisites for open source
3. How to do open source(resources)
4. Importance

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Developer-Swati** [comment]
Hello @anmode  please suggest me some blog topics if you do not agree with the above one . I will be happy to work on that under Hacktober Fest 2023

**Comment by anmode** [comment]
hi, there is blog feature , you just need to make it work. for now you can json and take data from json. Tommorow I'll provide you api to create blog and fetch blogs and fetch blog by ID so you can work on feature... are your ready? let me know

**Comment by Developer-Swati** [comment]
Yeah sure

**Comment by anmode** [comment]
Cool then for now you can use json for local saving and retriving the blog data after words we will change that with connecting the backend!

**Comment by Touseef-md** [comment]
Hey @anmode , I would like to work on this. Please assign this to me.

**Comment by anmode** [comment]
I'll change it to make blog active! to create some blogs.

**Comment by Touseef-md** [comment]
Could @anmode  you please elaborate a little, what exactly I need to do?

**Comment by ShivamAgarwal-code** [comment]
@anmode can you please assign me this issue..
