### ISSUE TITLE
🐞 [BUG] - Sign In / Up form doesn't have form validation

### ISSUE THREAD

**Issue by vatsalsinghkv** [anmode/Move-to-nextJS#797]
### Description

Sign in and Sign up form doesn't have proper form validation at the frontend, like you can make request without typing email and password, which creates bad user experience.

I'd like to add form validations at the frontend on these sign in and sign up forms.

### Current behaviour

Forms making request without any inputs

### Expected behaviour

It should let the user know to write valid email & password before making request to the backend

### Reproduction steps

```bash
1. Go to sign in / sing up page
2. Enter login / register without any input
```

### Screenshots

<img width="1440" alt="Screenshot 2023-10-28 at 8 19 02 PM" src="https://github.com/anmode/grabtern-frontend/assets/68834718/074e6ebd-6395-46ec-ab85-fefe7290b16f">

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by soulmini** [comment]
can you assign me @vatsalsinghkv

**Comment by anmode** [comment]
sure

**Comment by Yash-Ainapure** [comment]
Heyy @anmode , could you assign me this issue?
