### ISSUE TITLE
🚀 [Feature Request] - Dashboard Tour 

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#799]
### Is your feature request related to a problem ? Please describe. ✍️

1. Enhancing the UI of adding session page form
2. Listed session UI needs to be fixed
3. button position

and mobile version opitmization

### Describe briefly how you would implement this enhancement.

```bash
Login to dashboaord
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by rishuraj1** [comment]
Hi, @anmode I am willing to work on this one, please assign this to me

**Comment by anmode** [comment]
Hii rishu there is a PR going on in this direction. Can you create a dashboard tour UI?? when mentor/user logged in they can hve tour like all features of dashboard. now popup will have arrow and message with next or skip tour button.!

**Comment by rishuraj1** [comment]
@anmode  yeah, sure sounds fun. I will work on that

**Comment by anmode** [comment]
> @anmode yeah, sure sounds fun. I will work on that

Cool!
