### ISSUE TITLE
🚀 [Feature Request] - Proper table to handle and show data in sessions

### ISSUE THREAD

**Issue by rishuraj1** [anmode/Move-to-nextJS#808]
### Is your feature request related to a problem ? Please describe. ✍️

The sessions table is not optimized to handle and display data .

We can use packages like tanstack react table to achieve the desired functionality.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1
2. Step 2
3. Step 3
```

### Additional context or screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/47839626/33e1fef9-5f33-4414-89ee-0d8649864ba6)

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
@rishuraj1 if would be great if you can fix this last issue... Congrats you won grabtern swagkit!

**Comment by rishuraj1** [comment]
@anmode yes I will fix this asap
