### ISSUE TITLE
🐞 [BUG] - Inconsistent design in forms

### ISSUE THREAD

**Issue by vatsalsinghkv** [anmode/Move-to-nextJS#811]
## Visual Issues:

<img width="1440" alt="Screenshot 2023-11-17 at 8 05 24 PM" src="https://github.com/anmode/grabtern-frontend/assets/68834718/efd3ac97-a0e6-469e-b708-57fe6eaf29a1">

### Current behaviour

Right now in the forms whenever we put values with auto-complete we can this inconsistent background which doesn't fit with the theme. I would like to fix this issue

### Expected behaviour

Even on auto-complete the background background should be aligned with the theme.

### Reproduction steps

```bash
1. Go to https://grabtern-frontend-7rfndbnbq-anmode.vercel.app/auth/register
2. Click on input fields and fill the value with auto-complete
```

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

GrabSwagKit

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by vatsalsinghkv** [comment]
@anmode I would like to fix this visual issue.

**Comment by Nitinshukla88** [comment]
Please assign me this issue @anmode
