### ISSUE TITLE
🐞 [BUG] - Dark Mode is not working

### ISSUE THREAD

**Issue by Surajit0573** [anmode/Move-to-nextJS#814]
### Description

The button created at the top corner for switching between dark and light mode is not working.

### Current behaviour

Currently, The website is only available in light mode. And nothing happens on clicking the "sun" button.

### Expected behaviour

That button should switch modes.

### Reproduction steps

```bash
1. Go to 'home page'
2. Click on '"sun" button'
3. See error
```

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/111490250/eb422204-1af4-4192-ad18-8055a60c3823)

### Browsers

Chrome, Microsoft Edge

### OS

Windows

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Surajit0573** [comment]
I also want to fix this bug, you can assign me if approved.

**Comment by anmode** [comment]
cool! if you wanna carry forward this issue if dark mode....there could be multiple pRs. targetting one feat at a time.. like mentor dashboard -> dark mode , user dashboard --> dark mode
