### ISSUE TITLE
🚀 [Feature Request] - Title

### ISSUE THREAD

**Issue by GitWiz01** [anmode/Move-to-nextJS#816]
### Is your feature request related to a problem ? Please describe. ✍️

Designing and revamping New logo

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Analyzing the target audience and current market trend
2. Designing and revamping the design base
3. Implementing and Reviewing in Figma
```

### Additional context or screenshots

Hello Maintainer,
I'm a UI/UX developer
I have currently designed and revamped "Synclify" a google extension used by millions of people
I would like to contribute in improving the design of your logo and if possible the website also.

Please assign me this issue under CodePeak23

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool

**Comment by GitWiz01** [comment]
Thanks @anmode can you also put a label of codepeak 23 as I currently registered to it

**Comment by GitWiz01** [comment]
> Thanks @anmode can you also put a label of codepeak 23 as I currently registered to it

Please add it
