### ISSUE TITLE
🚀 [Feature Request] - Animations to website 

### ISSUE THREAD

**Issue by aindree-2005** [anmode/Move-to-nextJS#818]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 npm install gsap
2. Step 2 add gsap in dependencies
3. Step 3 use gsap to add animations to the overall project. I can start with just one page and make a pr. Then I'll make a pr for other pages!
```

### Additional context or screenshots

CodePeak 2023

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
animation where? please explain

**Comment by aindree-2005** [comment]
> animation where? please explain

@anmode Having animations Like the  mentor cards and other text blocks flow in  and add pop-up effect to some of the divs and all that

**Comment by anmode** [comment]
ah! ok you can give a try but I'm not sure ...means if it look good then I'll accpt!

**Comment by lightlessdays** [comment]
I would like to contribute to this. Can I be assigned this issue? I am good with GSAP.

**Comment by anmode** [comment]
yeah sure
