### ISSUE TITLE
🐞 [BUG] - Working of The Footer Subscribe button

### ISSUE THREAD

**Issue by Hemant2335** [anmode/Move-to-nextJS#820]
### Description

When button is Clicked it should either send some error  or the Success warning but it just shows a loading circle that might me the case that the button logic is not there  

### Current behaviour

Doesn't return anything other than Loading circle  

### Expected behaviour

Should Return some Error or Success Warning and should be working 

### Reproduction steps

```bash
1. Go to 'Footer of the Website'
2. Click on 'Subscribe button'
4. See the Loading Circle
```

### Screenshots

Video :
[Screencast from 2023-12-13 08-01-54.webm](https://github.com/anmode/grabtern-frontend/assets/85656999/197c8a87-9077-4b03-bd69-8d0b57774242)

### Browsers

Chrome

### OS

Linux

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
oh yes! please test it thoroughly by entering email too! and then wrong email

**Comment by Hemant2335** [comment]
@anmode Like I have Added the Email Authentication Param now they are working fine but when hitting the desired route to back end I think there is some issue because  it is Returning with status code 500. Should I check over there too Or do i just Pull a PR

**Comment by anmode** [comment]
you can just pull a pR! I'll check it with backend once
