### ISSUE TITLE
🐞 [BUG] - Dark mode is disabled

### ISSUE THREAD

**Issue by Souvik34** [anmode/Move-to-nextJS#824]
### Description

Dark mode is inactive . Please assign me the task

### Current behaviour

There is no function.

### Expected behaviour

When click, the website should be in dark mode.

### Reproduction steps

```bash
1. Go to 'Homepage'
2. Click on 'sun button'
3. Scroll down to 'top'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Souvik34** [comment]
Please assign me this task

**Comment by BroLetsCodeIt** [comment]
I am working on this
