### ISSUE TITLE
🚀 [Feature Request] - Replace old twitter logo with new logo

### ISSUE THREAD

**Issue by antriksh-9** [anmode/Move-to-nextJS#825]
### Is your feature request related to a problem ? Please describe. ✍️

On the website under footer section the twitter logo is still the old one. 
It needs to be updated.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Replace the old twitter icon with new one.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

false

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
cool!

**Comment by antriksh-9** [comment]
Hey @anmode can I proceed?

**Comment by anmode** [comment]
hi @antriksh-9 ... you can create pr for it!
