### ISSUE TITLE
🚀 [Feature Request] - Sepration design for website

### ISSUE THREAD

**Issue by GitWiz01** [anmode/Move-to-nextJS#832]
### Is your feature request related to a problem ? Please describe. ✍️

Section separation for website and more defined view to be made

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Creating a rough wireframe for the existing site layout
2. Analyzing the various components of the website to be separated
3. Finally Generating a more clear view for whosoever visits the site
```

### Additional context or screenshots

Also, please add codepeak 23 label on this issue, as I have also registered for it

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
wow! cool go ahead
