### ISSUE TITLE
🐞 [BUG] - Adding name validtion in contact section form 

### ISSUE THREAD

**Issue by Ayusht777** [anmode/Move-to-nextJS#834]
### Description

When user types name it should not contains special symbols or number  

### Current behaviour

it accepting special symbols and number in name filed 

### Expected behaviour

it should a proper error not valid name 

### Reproduction steps

```bash
1. Go to CONTACT PAGE WHERE GET IN TOUCH FORM 
2. Click on NAME
3. Enter your name 
4. See error
```

### Screenshots

![image](https://github.com/anmode/grabtern-frontend/assets/106388215/551d6242-9496-4f9e-bd91-d98ab44a8540)

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Please go for it!... liked it

**Comment by Ayusht777** [comment]
can you add kwoc label to it

**Comment by Ayusht777** [comment]
@anmode  created pr
