### ISSUE TITLE
🐞 [BUG] - Unrelated files changes --PWA thing

### ISSUE THREAD

**Issue by anmode** [anmode/Move-to-nextJS#837]
### Description

Avoid modifying files related to the PWA. See if those changes are necessary. can be done at build process once. these should not come in git history

### Current behaviour

these modify on every build or running dev server ----seems unrelated changes

### Expected behaviour

These should not be changed ideally.. if getting changes then bare minimum should not come in git history

### Reproduction steps

```bash
Just run the server.
```

### Screenshots

<img width="266" alt="Screenshot 2024-07-09 at 10 38 55 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/4be7d11a-fe9a-441f-a852-44a2b2d38267">

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Mac

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by unknown91tech** [comment]
There isn't a docker file in the project but it says in the descriptiion that docker is used
