### ISSUE TITLE
🐞 [BUG] - Subscribe Feature is not working.

### ISSUE THREAD

**Issue by Shariq2003** [anmode/Move-to-nextJS#855]
### Description

The subscribe feature is not working, not even shows any popup of success of failure.

https://github.com/user-attachments/assets/8a3563ec-baad-424c-acd3-4aeb57f90265

### Current behaviour

Not Working

### Expected behaviour

At least have to show a popup of success or failure.

### Reproduction steps

```bash
.
```

### Are you contributing for a program ?

Other - GSSOC Ext

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by tobiasrahul** [comment]
Hey can you please assign this to me as i have good experience as a we developer as i worked as an intern at Metacrafters
