### ISSUE TITLE
🚀 [Feature Request] - Add Missing Meta Tags for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [anmode/Move-to-nextJS#858]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag


Labels:
- GSSoC
- Hacktoberfest
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2023, Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

@anmode Please assign this issue to me (@myselfshivams).

**Comment by itshivams** [comment]
@anmode Please assign the task to me to start working on SEO

**Comment by gaurkrutika** [comment]
@anmode please assign this to me
