### ISSUE TITLE
Inconsistent Card Sizes in Review Section

### ISSUE THREAD

**Issue by iamsaura8h** [anmode/Move-to-nextJS#862]
### Description

Hey @anmode ,

As a front-end and UI/UX developer, inconsistencies in a web app's design really stand out to me, and I’ve noticed one on grabtern-frontend. There is an issue with inconsistent card sizes for the review cards, which disrupts the uniformity of the layout.

Please refer to the screenshot below for clarification:
<img width="960" alt="is8" src="https://github.com/user-attachments/assets/1fb90b09-aaf3-4a52-b5d5-0562ff602b2e">

Please assign me this issue with labels `gssoc-ext` and `hacktoberfest-accepted` so i can start working on it right away.

### Current behaviour

There is no fixed size for cards in Review Section.

### Expected behaviour

The Size of the Cards should be consistent

### Reproduction steps

```bash
None
```

### Screenshots

![DESCRIPTION](LINK.png)
<img width="960" alt="is8" src="https://github.com/user-attachments/assets/e2a3ff6f-23c5-4e1e-a528-c719e72a9771">

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sanchitbajaj02** [comment]
Hi @iamsaura8h 
Thanks for pointing out the inconsistency. Please take up this issue and make it consistent

**Comment by sameer-soni** [comment]
@iamsaura8h are you still working on this? If not, @Sanchitbajaj02 can I get assigned?

**Comment by Sanchitbajaj02** [comment]
Hi @sameer-soni 
since I didn't get any response, I am assigning this to you

**Comment by sameer-soni** [comment]
@Sanchitbajaj02 i have fixed this, please add the label of hactoberfest-accepted and gssoc-ext in that pr before merging it
