### ISSUE TITLE
🚀 [Feature Request] - Adding Scrollbar on the Homepage

### ISSUE THREAD

**Issue by AnanteshG** [anmode/Move-to-nextJS#869]
### Is your feature request related to a problem ? Please describe. ✍️

I would like to request the addition of a scrollbar on the homepage to improve the user experience because it is difficult to scroll to the end without a scrollbar.

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Navigate to homepage.
2. Observe that scrollbar is not available.
```

### Additional context or screenshots

![Screenshot 2024-10-06 224847](https://github.com/user-attachments/assets/e9f8f8d1-133a-4b17-be2b-545d5bfaff9c)

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sanchitbajaj02** [comment]
Hi @AnanteshG 
Yeah, the feature can fulfil the visual as well as functional needs. Please make sure the scrollbar must adhere to the theme to make it visually appealliing

**Comment by kartik3110** [comment]
Please assign me this issue i can make the PR by today itself
