### ISSUE TITLE
Add icons to NavLinks in the Navbar

### ISSUE THREAD

**Issue by Devaki01** [anmode/Move-to-nextJS#872]
Hello,
Can I contribute by adding attractive icons to the NavLinks present on the navbar section.

![image](https://github.com/user-attachments/assets/b345c19a-ff7d-444f-941b-e136b70f21d0)

Please assign me this issue under ggsoc'24 and hacktoberfest.
Thank you

**Comment by Sanchitbajaj02** [comment]
Hey @Devaki01 
The idea seems good, but does it match the overall theme and aesthetic of the application?

**Comment by Devaki01** [comment]
> Hey @Devaki01 The idea seems good, but does it match the overall theme and aesthetic of the application?

yes. The screenshot I added above is just a sample of my previous work. I will work on this issue keeping in mind the theme and aesthetic of your application.

**Comment by Shahharshii** [comment]
Hello,
I would request to assign me this issue and also merge this pr of mine
