### ISSUE TITLE
🐞 [BUG] - Adjustment of the spiner location to be in center to enhance the user experience.

### ISSUE THREAD

**Issue by tarunkumar2005** [anmode/Move-to-nextJS#876]
### Description

Adjustment of the spiner location to be in center to enhance the user experience.  The spiner is not in the correct position i think it should be in center of the page horizontally on the mentor page i would like to do that.

@anmode Assign this to  me under gssoc 2024 ext and hacktoberfest i would like to work on this issue.

### Current behaviour

It is in one side of the page which is not right.

### Expected behaviour

It should be in center so that easily it can be seen and well aligned.

### Reproduction steps

```bash
...
```

### Screenshots

![image](https://github.com/user-attachments/assets/d04f2a3e-2b8c-41ee-a79f-d7f194368f0f)

### Are you contributing for a program ?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sanchitbajaj02** [comment]
Hi @tarunkumar2005 
please proceed and fix this issue, thanks

**Comment by sameer-soni** [comment]
@Sanchitbajaj02 is this issue solved? if not, I'm interested.

**Comment by tarunkumar2005** [comment]
@sameer-soni See i have open PR so means it is solved
