### ISSUE TITLE
🚀 [Feature Request] - Title: Add FAQs 

### ISSUE THREAD

**Issue by meghanakn473** [anmode/Move-to-nextJS#881]
### Is your feature request related to a problem ? Please describe. ✍️

i want too implement FAQs pop up model to bottom down right side, wen user clicks on it faqs pop ups on screen

@anmode please assign me this task

### Describe briefly how you would implement this enhancement.

```bash
.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by arpit74170** [comment]
pls assign this task to me i will add the faq part with some intresting colors
