### ISSUE TITLE
🚀 [Feature Request] - Title : Hovering effects on featured internships

### ISSUE THREAD

**Issue by meghanakn473** [anmode/Move-to-nextJS#882]
### Is your feature request related to a problem ? Please describe. ✍️

@anmode please assign me this task

### Describe briefly how you would implement this enhancement.

```bash
.
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by itznayan** [comment]
please assign this issue to me .
