### ISSUE TITLE
🐞 [BUG] Google Authentication Not Working

### ISSUE THREAD

**Issue by simmi-verma** [anmode/Move-to-nextJS#902]
### Description

: Users are experiencing issues when attempting to log in using Google authentication. The login process fails, and users are unable to access their accounts.

### Current behaviour

 Failed to open popup window on url : https://accounts.google.com/gsi/select?client_id=1094459761-ugk0m6u1bt4vmv8ceug51lpvur40uobp.apps.googleusercontent.com&ux_mode=popup&ui_mode=bottom_sheet&context=signup&as=b8SCA5Q4lS2ejHs1WLYppA&channel_id=438115777663eaa19daafcaaeb681c69fd805e9604c4a369be8de0439c1b0782&origin=https%3A%2F%2Fwww.grabtern.in. Maybe blocked by the browser?

**Comment by simmi-verma** [comment]
Add gssoc-ext and level 3 label

**Comment by Benjtalkshow** [comment]
Hello @simmi-verma 
Can i work on this. I can easily fix this issue.

**Comment by anmode** [comment]
Hi, actually we have blocked gauth in dev mode due to security, Thanks for pointing out please feel free to create issues if you find any  bug!
