### ISSUE TITLE
🚀 [Feature Request] - Create internship tips page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [anmode/Move-to-nextJS#911]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement
Create internship tips page

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Creates a internship tips page which contains tips to grab any intern
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by anmode** [comment]
Thanks but really not needed. pleaes it would be a great help look out dashboard or session booking page. You will really find bugs
